# Generated by Django 2.2.19 on 2021-03-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210308_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='extract',
            new_name='observations',
        ),
    ]
